<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <Configurations>Debug;Release;DebugL</Configurations>
      <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Scripts\cleanup-script.ts">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Meshmakers.Octo.Runtime.Engine.MongoDb" Version="$(OctoVersion)" />
      <ProjectReference Include="..\SystemBotCkModel\SystemBotCkModel.csproj" />
    </ItemGroup>

</Project>
