<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <None Update="Scripts\cleanup-script.ts">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\octo-common-services\src\octo-construction-kit-engine-mongodb\src\Runtime.Engine.MongoDb\Runtime.Engine.MongoDb.csproj" />
    </ItemGroup>

</Project>
