$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
- typeId: AttributeAggregateConfiguration
  derivedFromCkTypeId: ${System}/Entity
  attributes:
  - id: ${System}/Enabled
    name: IsAutoCompleteEnabled
  - id: ${this}/AutoCompleteFilter
    name: AutoCompleteFilter
  - id: ${this}/AutoCompleteLimit
    name: AutoCompleteLimit
  associations:
  - id: ${this}/Configures
    targetCkTypeId: ${System}/Entity
