<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OctoSkipCkCompile Condition="'$(Configuration)'=='Release'">true</OctoSkipCkCompile>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)'!='DebugL'">
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.Contracts" Version="3.0.26" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.SourceGeneration" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="3.0.26" />
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="3.0.26" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="3.0.26" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)'=='DebugL'">
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.Contracts" Version="999.0.0" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.SourceGeneration" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="999.0.0" />
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="999.0.0" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="999.0.0" PrivateAssets="all" />
    </ItemGroup>
</Project>
