<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Octo.Backend.Jobs</AssemblyName>
        <IsPackable>true</IsPackable>
        <PackageId>Meshmakers.Octo.Backend.Jobs</PackageId>
        <RootNamespace>Meshmakers.Octo.Backend.Jobs</RootNamespace>
        <OutputPath>..\..\bin\$(Configuration)\</OutputPath>
        <DocumentationFile>..\..\bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
        <NoWarn>1701;1702;CS8002</NoWarn>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.Core" Version="1.8.18" />
        <PackageReference Include="RestSharp" Version="112.1.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(OctoConstructionKitPath)src\Runtime.Engine.MongoDb\Runtime.Engine.MongoDb.csproj" />
        <ProjectReference Include="$(OctoCommonServicesPath)src\Common\Common.csproj" />
        <ProjectReference Include="..\SystemBotCkModel\SystemBotCkModel.csproj" />
    </ItemGroup>


</Project>