<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <Configurations>Debug;Release;DebugL</Configurations>
      <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="BotTexts.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>BotTexts.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="BotTexts.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>BotTexts.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
