//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotServices.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BotServices.Resources.BotTexts", typeof(BotTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Backend_BotServices_AccessDenied_Title {
            get {
                return ResourceManager.GetString("Backend_BotServices_AccessDenied_Title", resourceCulture);
            }
        }
        
        public static string Backend_BotServices_AccessDenied_Body {
            get {
                return ResourceManager.GetString("Backend_BotServices_AccessDenied_Body", resourceCulture);
            }
        }
        
        public static string Backend_BotServices_Api_FullAccess {
            get {
                return ResourceManager.GetString("Backend_BotServices_Api_FullAccess", resourceCulture);
            }
        }
        
        public static string Backend_BotServices_Api_ReadOnlyAccess {
            get {
                return ResourceManager.GetString("Backend_BotServices_Api_ReadOnlyAccess", resourceCulture);
            }
        }
        
        public static string Backend_BotServices_UserSchema_Swagger_DisplayName {
            get {
                return ResourceManager.GetString("Backend_BotServices_UserSchema_Swagger_DisplayName", resourceCulture);
            }
        }
        
        public static string Backend_BotServices_UserSchema_BotServices_DisplayName {
            get {
                return ResourceManager.GetString("Backend_BotServices_UserSchema_BotServices_DisplayName", resourceCulture);
            }
        }
    }
}
